### ISSUE TITLE
bind_address overwritten

### ISSUE THREAD

**Issue by jangrewe** [debops/ansible-mariadb_server#35]
On my Ubuntu 16.04 box the `mariadb_server__bind_address` setting gets overwritten by the settings in `/etc/mysql/mariadb.conf.d/50-server.cnf` from the `mariadb-server-10.0` package.

Maybe it makes sense to set those files to `absent`, or at least check them for those settings, too?

**Comment by drybjed** [comment]
I suppose that the name and location of the configuration file the role generates will need to be changed on the newest OS releases like Xenial and Stretch to account for new MariaDB configuration layout. Thanks for the bug report.

**Comment by mmack** [comment]
I have the same problem. Any update on this?

**Comment by mmack** [comment]
```
tasks:
- lineinfile:
    dest: /etc/mysql/mariadb.cnf
    regexp: 'EOF'
    line: '!includedir /etc/mysql/conf.d/'

```
This sets the custom config at EOF again...
