### ISSUE TITLE
Can't get auto backup work, because referenced to a wrong variable.

### ISSUE THREAD

**Issue by beata** [debops/ansible-mariadb_server#38]
https://github.com/debops/ansible-mariadb_server/blob/master/tasks/configure_server.yml#L18

```
- name: Setup automysqlbackup configuration
  template:
    src: 'etc/default/automysqlbackup.j2'
    dest: '/etc/default/automysqlbackup'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: mariadb_server_backup|d()  # which should be `mariadb_server__backup`
```
